{
 "title": "Hermes dashboard CND",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "request_id",
    "query": {
     "query": "label_values(hermes_requests_sent,id)"
    }
   },
   {
    "name": "Logs_datasource",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "Metrics_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Instrumented", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success ratio (last)",
   "type": "gauge",
   "description": "Shows the percentage of requests that were answered with expected result codes",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hermes_responses_rcv_ok{id=~\"$request_id\"}) / sum(hermes_requests_sent{id=~\"$request_id\"}) *100"
    }
   ]
  },
  {
   "title": "Requests sent/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(sum(hermes_requests_sent{id=~\"$request_id\"}[5m])))"
    }
   ]
  },
  {
   "title": "Response times (ms)",
   "type": "timeseries",
   "description": "This panel shows the response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 12, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m]",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Responses received/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(sum(hermes_responses_rcv_ok{id=~\"$request_id\"}[5m])))"
    }
   ]
  },
  {
   "title": "RT (last)",
   "type": "stat",
   "description": "This gauge shows the latest average of response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GET debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GET logs",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "GET | stats by (_stream) count() hits | sort by (hits) desc limit 5"
    }
   ]
  },
  {
   "title": "GET logs - server",
   "type": "logs",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "_stream: {k8s.container.name=\"server-mock\"} AND \"GET\" | _time:10s"
    }
   ]
  }
 ]
}